### ISSUE TITLE
Docker Compose instructions are not instructions

### ISSUE THREAD

**Issue by LostOnTheLine** [akornatskyy/scheduler#815]
On the [Installation](https://github.com/akornatskyy/scheduler#installation) Instructions under **[Option 2: Running with Docker Compose](https://github.com/akornatskyy/scheduler#option-2-running-with-docker-compose)** you just say to `docker-compose up -d` but the Docker-Compose provided needs arguments, none of which are explained anywhere.

When run with a base build of the Docker-Compose it returns this error in the Logs
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.
       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```
Nowhere is anything given to say that that is required or that that needs to be added to the Docker-Compose file.
Typicvally this is done by listing the compose on the Readme Page then listing Variables needed

```yaml
version: '3'
services:
  db:
    container_name: db
    restart: always
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
        #command: postgres -c 'log_statement=all'
    networks:
      - db
  api:
    container_name: api
    depends_on:
      - db
    restart: always
    stop_signal: SIGINT
    image: akorn/scheduler
    ports:
      - 8080:8080
    environment:
      - DSN=postgres://postgres:@db:5432/postgres?sslmode=disable
      - POSTGRES_PASSWORD=<<ENTER YOUR PASSWORD HERE>>
    networks:
      - api
      - db
volumes:
  db:
    driver: local
networks:
  db:
  api:
```

Variables:
- **POSTGRES_PASSWORD**= You need to create a password but it doesn't look like you ever need to use that password as it seems to only be used internally

**Comment by dagid4** [comment]
```
docker run -d --restart=always --name scheduler-db -v scheduler-db:/var/lib/postgresql/data -e "POSTGRES_DB=postgres" -e "POSTGRES_PASSWORD=scheduler" postgres:12-alpine

docker run -d --restart=always --name scheduler --link scheduler-db:scheduler-db -p 8080:8080 -e "DSN=postgres://postgres:@scheduler-db:5432/postgres?sslmode=disable" -e "PGPASSWORD=scheduler" akorn/scheduler
```

**Comment by CoomInPickle** [comment]
hey @LostOnTheLine, i was able to use the yml, altho i cant access the webui for it with the port 8080.
the stack always exits with the error 

`2023/05/13 23:00:44 ERR: failed to apply migrations: dial tcp 127.0.0.1:5432: connect: connection refused`

**Comment by LostOnTheLine** [comment]
> hey @LostOnTheLine, i was able to use the yml, altho i cant access the webui for it with the port 8080. the stack always exits with the error
> 
> `2023/05/13 23:00:44 ERR: failed to apply migrations: dial tcp 127.0.0.1:5432: connect: connection refused`

What yaml did you use? The one from `/misc/docker/docker-compose.yaml` or the one I outlined? The one I outlined wasn't a fuctional one, it was an example of how things should be but aren't, but the information needed was not present. 

I have updated it using the information from @dagid4's post, but haven't tested it. It looks as though the `POSTGRES_PASSWORD=scheduler` database variable needs to match a variable `PGPASSWORD=scheduler` in the API. 

I personally have given up on trying to use this because the poorly written compose & lack of a response to issues gives me little faith in the development team.

**Comment by CoomInPickle** [comment]
> > hey @LostOnTheLine, i was able to use the yml, altho i cant access the webui for it with the port 8080. the stack always exits with the error
> > `2023/05/13 23:00:44 ERR: failed to apply migrations: dial tcp 127.0.0.1:5432: connect: connection refused`
> 
> What yaml did you use? The one from `/misc/docker/docker-compose.yaml` or the one I outlined? The one I outlined wasn't a fuctional one, it was an example of how things should be but aren't, but the information needed was not present.
> 
> I have updated it using the information from @dagid4's post, but haven't tested it. It looks as though the `POSTGRES_PASSWORD=scheduler` database variable needs to match a variable `PGPASSWORD=scheduler` in the API.
> 
> I personally have given up on trying to use this because the poorly written compose & lack of a response to issues gives me little faith in the development team.

both by now, but i just cant access the webinterface with the normal ip and port i use, i made sure i use the correct port but with no luck. by now im trying jenkins do do it for me but is really hard and isnt the right thing for my needs

**Comment by lukedoomer** [comment]
```
version: '3'
services:
  scheduler-db:
    container_name: scheduler-db
    restart: always
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - scheduler-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=scheduler
    # command: postgres -c 'log_statement=all'
    networks:
      - db
  scheduler-api:
    container_name: scheduler-api
    depends_on:
      - scheduler-db
    restart: always
    stop_signal: SIGINT
    image: akorn/scheduler
    ports:
      - 8080:8080
    environment:
      - DSN=postgres://postgres:scheduler@scheduler-db:5432/postgres?sslmode=disable
    networks:
      - api
      - db
volumes:
  db:
    driver: local
networks:
  db:
  api:
```

this compose.yaml works me.
This project doesn't suit my need so I removed it eventually. it has only ONE type of action, which is sending HTTP request.
